# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0227_inline_url_embed_preview_default_off'),
        ('zerver', '0228_userprofile_enable_all_favicon_dekstop_notifications'),
    ]

    operations = [
    ]